'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=['categories','categoryFilters','forGroups'];
const readonly=!!window.SCOUT_TAXONOMY_SNAPSHOT;
let report=null, pending=null, busy=false;
const dirty=new Set();
function message(text,error=false){$('#message').textContent=text;$('#message').className=error?'error':'';}
function assertClean(except){if([...dirty].some(f=>f!==except))throw Error('Save the other edited review first, or reload to discard it.');}
function reviewer(){const s=$('#reviewer').value.trim();if(!s)throw Error('Enter your name first.');return s;}
async function api(action,body){const response=await fetch(`/api/classifications/${report.projectId}/${action}`,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:report.revision,...body})});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
async function load(id){const r=await fetch(`/api/classifications/${id}/taxonomy`);const data=await r.json();if(!r.ok)throw Error(data.error||'Cannot open review');report=data;dirty.clear();render();}
async function run(fn){if(busy)return;busy=true;try{await fn();message('Saved review state.');}catch(e){if(e.name==='AbortError')message('Save cancelled. The migration remains in review.');else message(e.message,true);}finally{busy=false;}}
function para(text,cls=''){return `<p class="${cls}">${esc(text)}</p>`;}
function json(value){return `<pre>${esc(JSON.stringify(value,null,2))}</pre>`;}
function textarea(name,label,value=''){return `<label>${esc(label)}<textarea name="${esc(name)}">${esc(value)}</textarea></label>`;}
function notes(rows,key,saved={}){return Object.keys(rows).map((k,i)=>textarea(`${key}${i}`,`${k}${rows[k]?.summary?' — '+rows[k].summary:''}`,saved[k]||'')).join('');}
function groupCard(g,index){const r=g.review||{};return `<details class="group-card" data-group="${index}"><summary>${esc(g.group)} · ${g.currentCount} current / ${g.proposedCount} proposed resources</summary>
${para(g.definition||'Definition pending.')}${para('Aliases: '+(g.aliases.join(', ')||'none'))}
${para(`${g.coverage.researched} of ${g.coverage.members} member records researched; ${g.coverage.reviewed} reviewed for group usefulness; ${g.coverage.unreviewed} not reviewed; ${g.coverage.unresolved} with unresolved evidence.`,'count')}
${g.attention.map(t=>para(t,'conflict')).join('')}
${para('Categories: '+g.categories.map(c=>`${c.label} (${c.count})`).join(', '))}
${para(g.providerIdentityNote,'muted')}${para(g.providerClusters.filter(c=>c.count>1).map(c=>`${c.key}: ${c.count} program records`).join('; ')||'No multi-record provider cluster found.')}
${para('Possible duplicate records: '+(g.possibleDuplicates.map(ids=>ids.join(', ')).join('; ')||'none flagged'))}
${para('Shared members: '+(g.overlaps.map(o=>`${o.group}: ${o.count}`).join('; ')||'none'))}
<div class="scroll-table"><table><thead><tr><th>Resource</th><th>Membership</th><th>Research</th></tr></thead><tbody>${g.members.map(m=>`<tr><td>${esc(m.name)}<br><small>${esc(m.id)}</small></td><td>${m.current?'Current':'Not current'} → ${m.proposed?'proposed member':'proposed removal'}</td><td>${m.researched?'Completed classification research':'Not researched'}${m.unresolved?'; unresolved evidence':''}${m.groupEvidence?`<details><summary>Group evidence</summary>${para(m.groupEvidence.reason)}${para(m.groupEvidence.excerpt)}${para(m.groupEvidence.source)}</details>`:''}</td></tr>`).join('')}</tbody></table></div>
${r.outcome?para(`${r.stale?'STALE recommendation':'Saved recommendation'}: ${r.outcome}. ${r.practicalUse} ${r.reason} — ${r.reviewer}`,'conflict'):''}
${readonly?(r.memberDispositions?json(r.memberDispositions):''):`<form data-kind="group" data-index="${index}"><p>These outcomes are recommendations. They do not rename labels, remove members, or change the location app.</p><label>Outcome <select name="outcome">${['retain','clarify','change-prominence','merge','retire'].map(o=>`<option ${r.outcome===o?'selected':''}>${o}</option>`).join('')}</select></label>${textarea('use','Practical missionary question this group helps answer',r.practicalUse)}${textarea('reason','Reason, including coverage limits and possible missing memberships',r.reason)}
<label>Merge target (only for merge)<select name="target"><option value="">None</option>${report.groups.filter(x=>x.group!==g.group).map(x=>`<option ${r.target===x.group?'selected':''}>${esc(x.group)}</option>`).join('')}</select></label><label>Display preference (only for change-prominence)<select name="prominence"><option value="">None</option>${['prominent','all-groups'].map(x=>`<option ${r.prominence===x?'selected':''}>${x}</option>`).join('')}</select></label>
${g.members.map((m,i)=>textarea(`member${i}`,`${m.name}: retain, remove, or replace membership, and why`,r.memberDispositions?.[m.id])).join('')}<button>Save group recommendation</button></form>`}</details>`;}
function mappingRow(row,plan,index){const m=row.mapping||{};return `<details class="mapping"><summary>${esc(row.name)} · ${row.mapping?'mapping reviewed':'not reviewed'}${row.researchComplete?'':' · research incomplete'}</summary>
<div class="comparison"><div><h3>Current classifications</h3>${json(row.original)}</div><div><h3>Research proposal before category retirement</h3>${json(row.proposed)}</div></div>
${m.fields?`<h3>Reviewed final classifications</h3>${json(m.fields)}${para(m.note)}`:''}${row.blocked?para(row.blocked,'blocked'):''}
${row.conflictingFields.length?para('Later office edits oppose the research in: '+row.conflictingFields.join(', ')+'. Explain your choice in the mapping rationale.','conflict'):''}
<details><summary>Membership evidence and reasons</summary>${row.membershipDecisions.map(d=>para(`${d.value}: ${d.status}. ${d.reason} ${d.excerpt} Source: ${d.source}`)).join('')}</details>
${Object.values(row.unresolvedFindings).map(f=>para(f.summary,'conflict')).join('')}
${!readonly&&!plan.saved&&!plan.stale&&row.researchComplete?`<form data-kind="mapping" data-plan="${plan.id}" data-index="${index}"><p>The retiring categories and their Types are removed after these choices. The final result must have a supported service category.</p>${fields.map(f=>`<label>${esc(f)}<select name="${f}"><option value="proposed" ${m.choices?.[f]!=='current'?'selected':''}>Use research proposal with independent current edits</option><option value="current" ${m.choices?.[f]==='current'?'selected':''}>Keep current memberships</option></select></label>`).join('')}${textarea('note','Mapping rationale, including supported groups or why none applies',m.note)}${notes(row.requiredTypeDispositions,'type',m.typeDispositions)}${notes(row.unresolvedFindings,'finding',m.findingNotes)}<button>Save this resource mapping</button></form>`:''}</details>`;}
function planCard(p){const missing=p.rows.filter(r=>!r.researchSelected);return `<details class="migration-plan" data-plan="${p.id}" open><summary>Migration ${p.id}: ${esc(p.categoryIds.join(', '))} · ${p.reviewedCount}/${p.affectedIds.length} mappings reviewed${p.saved?' · saved':''}</summary>${para(p.reason)}${p.legacyCategoryIds.length?para('This same change set also retires old category aliases that point here: '+p.legacyCategoryIds.join(', ')+'. Their old labels must not restore the retired categories.','conflict'):''}
${para(`${p.rows.filter(r=>r.researchComplete).length} of ${p.rows.length} affected resources have completed research.`,'count')}
${p.saved?para('Saved package: '+p.saved.packageSha256):p.stale?para('STALE: source data or research changed. Create a new plan after research is ready.','conflict'):para('Category retirement is blocked until every resource mapping and the complete change set are reviewed.','conflict')}
${!readonly&&!p.saved&&missing.length?`<button type="button" data-select="${p.id}">Add ${missing.length} missing resources to classification research</button><p>This preserves completed research. New assignments require all usual research stages. Extending research makes this draft stale.</p>`:''}
${p.compatibilityBlockers.map(t=>para(t,'conflict')).join('')}${p.rows.map((r,i)=>mappingRow(r,p,i)).join('')}
${p.approval?para(`Whole change set approved by ${p.approval.reviewer}: ${p.approval.note}`):''}
${!readonly&&!p.saved&&!p.stale?`<form data-kind="approve" data-plan="${p.id}">${textarea('note','Whole change set review note',p.approval?.note)}<button ${p.ready?'':'disabled'}>Approve complete migration</button></form><button type="button" data-export="${p.id}" ${p.ready&&p.approval?'':'disabled'}>Save approved migration package</button>`:''}</details>`;}
function render(){if(!report)return;const open=[...document.querySelectorAll('details[open][data-group]')].map(d=>d.dataset.group);
$('#report').innerHTML=`<section><h2>${esc(report.office)}</h2>${report.historical?para('Historical development package — not current office data.','conflict'):''}${readonly?para('Read-only review snapshot. No package changes or approvals are made from this copy.','conflict'):''}${para(`Package v${report.packageVersion}: ${report.officeResourceCount} resources; ${report.researchedResourceCount} have completed classification research.`,'count')}${para(report.coverageNote)}${para('Package SHA-256: '+report.packageSha256,'muted')}</section><h2>Group usefulness</h2>${report.groups.map(groupCard).join('')}<h2>Complete category migrations</h2>${!readonly?`<form data-kind="plan"><section><p>Create one plan for all population categories being retired together. A plan inventories every affected resource, including resources outside the selected pilot.</p>${report.populationCategories.map((c,i)=>`<label><input type="checkbox" name="category${i}"> ${esc(c.label)} (${c.affectedCount} affected)</label>`).join('')}${textarea('reason','Purpose of this migration')}<button>Create complete migration draft</button></section></form>`:''}${report.plans.map(planCard).join('')}`;
for(const i of open){const el=document.querySelector(`details[data-group="${i}"]`);if(el)el.open=true;}
$('#save-confirmation').hidden=!pending;
}
function values(form,prefix,keys){return Object.fromEntries(keys.map((k,i)=>[k,form.elements[prefix+i].value.trim()]));}
$('#report').addEventListener('input',e=>{const f=e.target.closest('form');if(f)dirty.add(f);});
$('#report').addEventListener('submit',e=>{e.preventDefault();const form=e.target;run(async()=>{assertClean(form);const f=form.elements;let action,body;
if(form.dataset.kind==='group'){const g=report.groups[Number(form.dataset.index)];action='taxonomy-group';body={group:g.group,outcome:f.outcome.value,practicalUse:f.use.value,reason:f.reason.value,reviewer:reviewer(),memberDispositions:values(form,'member',g.members.map(m=>m.id)),target:f.target.value,prominence:f.prominence.value};}
if(form.dataset.kind==='plan'){action='taxonomy-plan';body={categoryIds:report.populationCategories.filter((c,i)=>f['category'+i].checked).map(c=>c.id),reason:f.reason.value};}
if(form.dataset.kind==='mapping'){const p=report.plans.find(p=>p.id===Number(form.dataset.plan)),r=p.rows[Number(form.dataset.index)];action='taxonomy-mapping';body={planId:p.id,resourceId:r.id,choices:Object.fromEntries(fields.map(k=>[k,f[k].value])),reviewer:reviewer(),note:f.note.value,findingNotes:values(form,'finding',Object.keys(r.unresolvedFindings)),typeDispositions:values(form,'type',Object.keys(r.requiredTypeDispositions))};}
if(form.dataset.kind==='approve'){action='taxonomy-approve';body={planId:Number(form.dataset.plan),reviewer:reviewer(),note:f.note.value};}
report=await api(action,body);dirty.clear();pending=null;render();});});
$('#report').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.select)run(async()=>{assertClean();const p=report.plans.find(p=>p.id===Number(b.dataset.select));report=await api('taxonomy-select',{resourceIds:p.rows.filter(r=>!r.researchSelected).map(r=>r.id)});render();});
if(b.dataset.export)savePackage(Number(b.dataset.export));});
async function savePackage(planId){if(busy)return;try{assertClean();}catch(e){message(e.message,true);return;}
// Open the picker in the click gesture, before preparing any export.
let handlePromise;try{handlePromise=window.showSaveFilePicker?window.showSaveFilePicker({suggestedName:`scout-taxonomy-${report.projectId}-${planId}.zip`,types:[{description:'Resource package',accept:{'application/zip':['.zip']}}]}):Promise.resolve(null);}catch(e){message(e.message,true);return;}
await run(async()=>{const handle=await handlePromise;const exported=await api('taxonomy-export',{planId});await load(report.projectId);
const response=await fetch(`/api/classifications/${report.projectId}/taxonomy-exports/${exported.exportId}`);if(!response.ok)throw Error('Could not download migration package');const blob=await response.blob();
if(globalThis.crypto?.subtle){const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==exported.manifest.packageSha256)throw Error('Downloaded bytes do not match the export.');}
if(handle){const stream=await handle.createWritable();try{await stream.write(blob);await stream.close();}catch(e){try{await stream.abort();}catch{}throw e;}report=await api('taxonomy-saved',{exportId:exported.exportId,packageSha256:exported.manifest.packageSha256});render();}
else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`scout-taxonomy-${report.projectId}-${planId}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);pending=exported;render();}});}
$('#confirm-saved').onclick=()=>run(async()=>{assertClean();if(!pending)throw Error('No pending download');report=await api('taxonomy-saved',{exportId:pending.exportId,packageSha256:pending.manifest.packageSha256});pending=null;render();});
$('#keep-review').onclick=()=>{try{assertClean();pending=null;render();message('Migration remains in review.');}catch(e){message(e.message,true);}};
$('#refresh').onclick=()=>run(async()=>{assertClean();if(report)await load(report.projectId);});
$('#projects').onchange=()=>run(async()=>{assertClean();pending=null;if($('#projects').value)await load($('#projects').value);});
window.addEventListener('beforeunload',e=>{if(dirty.size){e.preventDefault();e.returnValue='';}});
if(readonly){document.body.classList.add('snapshot');report=window.SCOUT_TAXONOMY_SNAPSHOT;render();}
else run(async()=>{const r=await fetch('/api/classifications'),data=await r.json();if(!r.ok)throw Error(data.error||'Cannot list projects');$('#projects').innerHTML='<option value="">Choose a project</option>'+data.projects.map(p=>`<option value="${p.id}">${esc(p.office)} · ${p.id}</option>`).join('');const id=new URLSearchParams(location.search).get('project');if(id&&data.projects.some(p=>String(p.id)===id)){$('#projects').value=id;await load(id);}});
